#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontRight,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int threshold = 15;

task main()
{
	// Mecanum style, with a threshold. The threshold avoids having
  // a joystick that is too sensitive throw off the direction of
  // robot.
  // http://www.robotc.net/blog/2011/11/22/vex-mecanum-drive-using-robotc/
  int X2 = 0, Y1 = 0, X1 = 0;

  if(abs(vexRT[Ch3]) > threshold) Y1 = vexRT[Ch3];
  if(abs(vexRT[Ch4]) > threshold) X1 = vexRT[Ch4];
  if(abs(vexRT[Ch1]) > threshold) X2 = vexRT[Ch1];

while (true){
  //Remote Control Commands
  motor[frontRight] = Y1 - X2 - X1;
  motor[backRight] =  Y1 - X2 + X1;
  motor[frontLeft] =  Y1 + X2 + X1;
  motor[backLeft] =   Y1 + X2 - X1;
}

}
